linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

linters:
  enable:
    - govet
    - errcheck
    - megacheck
    - goconst
    - gofmt
    - goimports
    - golint
    - ineffassign
  enable-all: false
  disable:
    - maligned
    - prealloc
