name: Slash Command - Run CI Checks

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  retrigger-checks:
    if: |
      github.event.issue.pull_request != null &&
      github.event.comment.body == '/checks'
    runs-on: ubuntu-latest

    steps:
      - name: Get PR branch name
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return pr.data.head.ref;
          result-encoding: string

      - name: Check out PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.pr.outputs.result }}

      - name: Set up Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and push empty commit
        run: |
          git commit --allow-empty -m "ci: re-run all checks via /checks"
          git push origin HEAD

      - name: Post confirmation comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✅ CI checks re-triggered by @${{ github.event.comment.user.login }} using `/checks`."
            });
